### ISSUE TITLE
Add About section

### ISSUE THREAD

**Issue by chirag-ghosh** [kossiitkgp/YAKW#18]
- Please refer to the [design](https://www.figma.com/file/Ig70QETLgR6Y0ZPj8ZJuTr/KOSS-Website-(Astro)?type=design&node-id=0-1&mode=design&t=Rf7FMFZJfeXlOp5P-0).
- Add the section [here](https://github.com/kossiitkgp/YAKW/blob/master/src/pages/index.astro).
- Ensure that the whole section is `100dvh` in height.

![image](https://github.com/kossiitkgp/YAKW/assets/75582834/853891de-d290-4db0-bb83-3dabb6a0b907)

**Comment by rajivharlalka** [comment]
The font specs? This size looks too cluterred.

**Comment by chirag-ghosh** [comment]
font currently used is in the figma file. Please decide on the text. You can try with different sizes in the figma file too.
