### ISSUE TITLE
Add Upcoming Events Section

### ISSUE THREAD

**Issue by chirag-ghosh** [kossiitkgp/YAKW#19]
- Please refer to the [design](https://www.figma.com/file/Ig70QETLgR6Y0ZPj8ZJuTr/KOSS-Website-(Astro)?type=design&node-id=160-2&mode=design&t=XmiA7KMwOlRNTNhH-0).
- Add the section [here](https://github.com/kossiitkgp/YAKW/blob/master/src/pages/index.astro).
- Ensure that the whole section is `100dvh` in height.

![image](https://github.com/kossiitkgp/YAKW/assets/75582834/df166fb7-4400-4100-bbf7-b852e7a73820)

**Comment by rajivharlalka** [comment]
How would the carousel shift in case of mobile? Left right buttons or swipe

**Comment by chirag-ghosh** [comment]
Swipe would be great. We should have automatic moves
