### ISSUE TITLE
Create floating navbar

### ISSUE THREAD

**Issue by chirag-ghosh** [kossiitkgp/YAKW#20]
- Please refer to the [design](https://www.figma.com/file/Ig70QETLgR6Y0ZPj8ZJuTr/KOSS-Website-(Astro)?type=design&node-id=0-1&mode=design&t=Rf7FMFZJfeXlOp5P-0).
- Create a navbar component [here](https://github.com/kossiitkgp/YAKW/tree/master/src/components).
- Use the component [here](https://github.com/kossiitkgp/YAKW/blob/master/src/layouts/Layout.astro).

![image](https://github.com/kossiitkgp/YAKW/assets/75582834/b96ee4b4-c1c9-4f45-87f6-b67aae894830)

**Comment by rajivharlalka** [comment]
Mobile design for this?

**Comment by chirag-ghosh** [comment]
Same. Just make it smaller. You are free to explore other variations though
