### ISSUE TITLE
Change about section text

### ISSUE THREAD

**Issue by chirag-ghosh** [kossiitkgp/YAKW#22]
Please come up with a brief about of the society for the about section in the homepage.
Note that it should be short and crisp considering we have a dedicated about page. This one is an at-a-glance description.

You need to replace [this](https://github.com/kossiitkgp/YAKW/blob/master/src/components/AboutSection.astro#L14-L17) text.

**Comment by proffapt** [comment]
How much short? Do you have a word limit in mind or design restricted limitation (like the text should go align with the height of the logo) or something like that?
