### ISSUE TITLE
Add Icon Credits

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/YAKW#48]
- Find out where the icons came from (See Figma file)
- [x] Add credits in the README
- [ ] Add credits in the footer (in the future)

**Comment by nischalon10** [comment]
Hey @harshkhandeparkar I would like to take this up! Can you assign it to me?

**Comment by harshkhandeparkar** [comment]
> Hey @harshkhandeparkar I would like to take this up! Can you assign it to me?

Sure!

**Comment by nischalon10** [comment]
Hey @harshkhandeparkar Can you help me find the figma file
